language: ruby
script:
- bundle exec rake test
cache: bundler
sudo: false
notifications:
  slack:
    secure: sCaUBjafl6YwuzuqIKQZVha/uIUrGJK+SNIMD2DgyHCdStb6Spw9+Zg6JvspZ0uK8qeWDPfZCrdbYXsr/YsAXCro3arJs8DJIdV8fLKpdKJPbMOFXEPsOE0QA2F5RnJA+7UvLmPhlliCtMLA5jn21KdvsLgNgWVr2iEP2X6HXnZ0fnpV+uv+fw64/qPXeE3cVUhQLduHTMsLMZm3Zas+GD3QYnMVsKX+81F3EAoa0a1ZFFvc5MGEGHXP+cmq3L2V99pleazg9AirxMARC4uWgBQbv2wqahnCkVl8FOGVDjkPOu08oM/3cmZo1fSzwwpdDqPpxALB37YA80w1YQG5Ll1vLlYfjwAGYJOAsFND1/+nqcFmfsXl/5yNLeHaFjJV3VRYm9nRXVDpzRsicwYtCjeQ6Xe1OyRwZQZPBe2FIZFFkonkUBUlDpmnFzOebQ2zS13QBy8LtBCs5SM6S01Z7O+dVbn31VfKJTL0Rg+tIj/ex9y7kE0A0Qyu64lcGbbj9WEZgGDU4sEX7c1EjA6wU8snCtvmTdZqkQ5oW7rYV9zHghYYp4kPYTAxauvvNf5GqzaG3jFac2wN6xj0Mj5vx7n7nG7TWDEx4TK7eY4zQC4G13tsnLlp8mPcay//nE62txHXLyYoPf62vgMPQ+gEmZV1jtjZDU8WRcaUkUQPTJY=
